zookeeper:
  image: confluentinc/cp-zookeeper
  hostname: zookeeper
  ports:
    - 2182:2181
  environment:
    SERVICE_NAME: zookeeper

kafka:
  image: confluentinc/cp-kafka:3.1.1
  hostname: kafka
  ports:
    - 9092:9092
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://$DOCKER_IP:9092"
    KAFKA_CREATE_TOPICS:
