resolver: lts-8.22

packages:
- '.'
- location:
    git: https://github.com/haskell-works/hw-kafka-client
    commit: d9c360a3eb8c977cb1aea5a53bb2d76e13721fb0
  extra-dep: true

extra-deps: []

flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
